
package Employees;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class Workers extends javax.swing.JFrame {

    Connection con;
    Statement stmt;
    ResultSet rs;
    int curRow = 0;
    
    public Workers() {
        initComponents();
        DoConnect();
    }
    
    public void DoConnect(){
        try{
            String host= "jdbc:derby://localhost:1527/Employees";
            String uName= "user1";
            String uPass= "user1";
            con= DriverManager.getConnection(host , uName , uPass );
            stmt= con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            String SQL = "SELECT * FROM Workers";
            rs= stmt.executeQuery(SQL);
            
            rs.next();
            int id_col= rs.getInt("ID");
            String id= Integer.toString(id_col);
            String first_name= rs.getString("First_Name");
            String last_name= rs.getString("Last_Name");
            String job= rs.getString("Job_Title");
            
            jTextField1.setText(id);
            jTextField2.setText(first_name);
            jTextField3.setText(last_name);
            jTextField4.setText(job);
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("textID");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("textFirstName");

        jTextField3.setText("textLastName");

        jLabel1.setText("Job Title ");

        jTextField4.setText("textJobTitle");

        jButton1.setText("First");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("last");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Update Record");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Delete Record");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("New Record");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Save New Record");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Cancel New Record");
        jButton9.setEnabled(false);
        jButton9.setHideActionText(true);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                    .addComponent(jTextField4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            if(rs.next()) {
                 int id_col= rs.getInt("ID");
            String id= Integer.toString(id_col);
            String first_name= rs.getString("First_Name");
            String last_name= rs.getString("Last_Name");
            String job= rs.getString("Job_Title");
            
            jTextField1.setText(id);
            jTextField2.setText(first_name);
            jTextField3.setText(last_name);
            jTextField4.setText(job);
                
            }
            else {
                 rs.previous();
            JOptionPane.showMessageDialog(this, "End of File ");
            }
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
           
        }
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            try {
            if(rs.previous()) {
                 int id_col= rs.getInt("ID");
            String id= Integer.toString(id_col);
            String first_name= rs.getString("First_Name");
            String last_name= rs.getString("Last_Name");
            String job= rs.getString("Job_Title");
            
            jTextField1.setText(id);
            jTextField2.setText(first_name);
            jTextField3.setText(last_name);
            jTextField4.setText(job);
                
            }
            else {
                 rs.next();
            JOptionPane.showMessageDialog(this, "Start of File ");
            }
        }
        catch (SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
           
        }
              
          
             
    
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            try{
                rs.first();
                int id_col= rs.getInt("ID");
            String id= Integer.toString(id_col);
            String first_name= rs.getString("First_Name");
            String last_name= rs.getString("Last_Name");
            String job= rs.getString("Job_Title");
            
            jTextField1.setText(id);
            jTextField2.setText(first_name);
            jTextField3.setText(last_name);
            jTextField4.setText(job);
            }
            catch(SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
                
            }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
             try{
                rs.last();
            int id_col= rs.getInt("ID");
            String id= Integer.toString(id_col);
            String first_name= rs.getString("First_Name");
            String last_name= rs.getString("Last_Name");
            String job= rs.getString("Job_Title");
            
            jTextField1.setText(id);
            jTextField2.setText(first_name);
            jTextField3.setText(last_name);
            jTextField4.setText(job);
            }
            catch(SQLException err) {
            JOptionPane.showMessageDialog(this, err.getMessage());
                
            }
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
          try{
              rs.deleteRow();
              
              stmt.close();
              rs.close();
              
              stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
              
              String SQL = "SELECT * FROM Workers";
              rs= stmt.executeQuery(SQL);
              
              rs.next();
            int id_col= rs.getInt("ID");
            String id= Integer.toString(id_col);
            String first_name= rs.getString("First_Name");
            String last_name= rs.getString("Last_Name");
            String job= rs.getString("Job_Title");
            
             jTextField1.setText(id);
            jTextField2.setText(first_name);
            jTextField3.setText(last_name);
            jTextField4.setText(job);
            
            JOptionPane.showMessageDialog(this, "Record Deleted");
              
                      
              
          }
          catch(SQLException err) {
              JOptionPane.showMessageDialog(this, err.getMessage());
              
          }
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         String first= jTextField2.getText();
         String last= jTextField3.getText();
         String job= jTextField4.getText();
         String ID= jTextField1.getText();
         
         int newID = Integer.parseInt(ID);
         
         try{
             rs.moveToInsertRow();
             
             rs.updateInt("ID", newID);
             rs.updateString("First_Name", first);
             rs.updateString("Last_Name", last);
             rs.updateString("Job_Title", job);
             
             rs.insertRow();
             
             stmt.close();
             rs.close();
             
             stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
             
             String SQL = "SELECT * FROM Workers";
             rs= stmt.executeQuery(SQL);
             
             rs.next();
             
             int id_col = rs.getInt("ID");
             String id = Integer.toString(id_col);
             String first2= rs.getString("First_Name");
             String last2= rs.getString("Last_Name");
             String job2= rs.getString("Job_Title");
             
            jTextField1.setText(id);
            jTextField2.setText(first2);
            jTextField3.setText(last2);
            jTextField4.setText(job2);
            
          jButton1.setEnabled(false);
          jButton2.setEnabled(false);
          jButton3.setEnabled(false);
          jButton4.setEnabled(false);
          jButton5.setEnabled(false);
          jButton6.setEnabled(false);
          jButton7.setEnabled(false);
          
          jButton8.setEnabled(true);
          jButton9.setEnabled(true);
          JOptionPane.showMessageDialog(this, "Record Saved");
             
             
         }
         catch(SQLException err){
             JOptionPane.showMessageDialog(this, err.getMessage());
             
         }
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         String first= jTextField2.getText();
         String last= jTextField3.getText();
         String job= jTextField4.getText();
         String ID= jTextField1.getText();
         
         int newID= Integer.parseInt(ID);
         try{
             rs.updateInt("ID" , newID);
             rs.updateString("First_Name" , first);
             rs.updateString("Last_Name", last);
             rs.updateString("Job_Title" , job);
             rs.updateRow();
             JOptionPane.showMessageDialog(Workers.this, "Updated");
         }
         catch(SQLException err){
             System.out.println(err.getMessage());
             
         }
             
         
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
          try{
              curRow = rs.getRow();
              
              jTextField2.setText("");
              jTextField3.setText("");
              jTextField4.setText("");
              jTextField1.setText("");
              
          jButton1.setEnabled(false);
          jButton2.setEnabled(false);
          jButton3.setEnabled(false);
          jButton4.setEnabled(false);
          jButton5.setEnabled(false);
          jButton6.setEnabled(false);
          jButton7.setEnabled(false);
          
          jButton8.setEnabled(true);
          jButton9.setEnabled(true);
          }
          catch(SQLException err){
              JOptionPane.showMessageDialog(this, err.getMessage());
              
          }
              
          
          
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
          try{
               curRow = rs.getRow();
              
              jTextField2.setText(rs.getString("First_Name"));
              jTextField3.setText(rs.getString("Last_Name"));
              jTextField4.setText(rs.getString("Job_Title"));
              jTextField1.setText(Integer.toString(rs.getInt("ID")));
              
              
          jButton1.setEnabled(true);
          jButton2.setEnabled(true);
          jButton3.setEnabled(true);
          jButton4.setEnabled(true);
          jButton5.setEnabled(true);
          jButton6.setEnabled(true);
          jButton7.setEnabled(true);
          
          jButton8.setEnabled(false);
          jButton9.setEnabled(false);
          }
          catch(SQLException err){
              JOptionPane.showMessageDialog(this, err.getMessage());              
          }
    
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">\
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Workers().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration                   
}

 


